### PR TITLE
Use multistage build to reduce image size

### PR DESCRIPTION
**Pull request by hnakamur**
Hi, first of all, thanks for sharing this Dockerfile!

This pull request reduces the container size to 22.5MB using docker multistage build (See [Use multi-stage builds | Docker Documentation](https://docs.docker.com/develop/develop-images/multistage-build/).

```
$ docker images --format '{{.Size}}' nginx-http3
22.5MB
```

It also adds a self-signed certificate and `nginx.conf` to listen on port 443 with quic.

### CODE REVIEW

**Comment by hnakamur** [comment]
And I build http3-client in quiche example in the same container 
in commit https://github.com/hnakamur/docker-nginx-http3/commit/e25c9bc10ecaf6f183f33eabb5ab1ae15e6d08fc
and confirmed http3-client connect to nginx with HTTP/3!

I also tried to build a separate http3-client container in commit
https://github.com/hnakamur/docker-nginx-http3/commit/da5a72ad3f8f596849bc2817ed609831b49a1ebb
but an error occurred when I ran http3-client to connect to nginx.

**Comment by hnakamur** [comment]
I figured out the correct step. I wrote it in the commit message at
https://github.com/hnakamur/docker-nginx-http3/commit/9d4c11119c08ec27743311d279cf9512fbccd38e

**Comment by RanadeepPolavarapu** [comment]
Changed base to `develop`. I'm going to add a test suite with Travis CI then we can merge all together into `master`.

**Comment by hnakamur** [comment]
Thanks!

**Comment by RanadeepPolavarapu** [comment]
Cheers! Thanks for the contribution. :smile:

**Pull request merged**
